# pre-commit hooks for roam-code
#
# Add to your .pre-commit-config.yaml:
#
#   repos:
#     - repo: https://github.com/Cranot/roam-code
#       rev: v11.0.0          # pin to a release tag
#       hooks:
#         - id: roam-syntax-check
#         - id: roam-health   # optional: slower, requires index
#
# All hooks run against the whole repository (pass_filenames: false).
# roam-syntax-check works without a pre-existing index.
# roam-health requires `roam init` to have been run first
# (calls ensure_index() internally and will auto-index if needed).
#
# Exit codes:
#   0  -- all checks passed
#   5  -- quality gate failed (issues found)
#   3  -- index missing (run `roam init` once to initialise the project)

- id: roam-syntax-check
  name: roam syntax check
  description: >
    Parse staged + unstaged files with tree-sitter and fail (exit 5) if
    any ERROR or MISSING nodes are found in the AST.  Works without a roam
    index -- files are parsed directly.
  entry: roam syntax-check --changed
  language: python
  pass_filenames: false
  always_run: true
  additional_dependencies: ['roam-code']

- id: roam-health
  name: roam health
  description: >
    Report the composite codebase health score (0-100) covering cycles,
    god components, bottlenecks, and layer violations.  Informational by
    default -- does not fail the commit.  Pair with the GitHub Action gate
    expression (health_score>=50) for enforced thresholds in CI.
  entry: roam health
  language: python
  pass_filenames: false
  always_run: true
  additional_dependencies: ['roam-code']

